package com.kyaKhaaye.Resources;

public class queries {
    public final static String[] queries = {
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (1,'biryani','hyedrabadi',f,t,f,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (2,'Aampapad','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (3,'Aappam','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (4,'Ada','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (5,'Anarsa','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (6,'Ariselu','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (7,'Bananachips','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (8,'Basundi','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (9,'Batatavada','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (10,'Bhaji','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (11,'Bhajia','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (12,'Bakarwadi','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (13,'Bhelpuri','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (14,'Bhoonja','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (15,'Bikaneribhujia','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (16,'Bonda','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (17,'Boondi','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (18,'AndaBhurji','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (19,'Bhurji-Paneer','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (20,'Chaat','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (21,'Cutlet','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (22,'Chakli','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (23,'ChanaJorGaram','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (24,'Chapati','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (25,'Chivda','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (26,'Cholebhature','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (27,'CholeKulche','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (28,'Dabeli','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (29,'Daldhokli','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (30,'Dahipuri','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (31,'Dahivada','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (32,'DahibaraAludam','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (33,'Dhokla','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (34,'Dosa','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (35,'Flattenedrice','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (36,'Gajarkahalwa','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (37,'Gajarkibarfi','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (38,'Ganthiya','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (39,'Gavvalu','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (40,'Ghever','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (41,'Ghugni','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (42,'Gujhia','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (43,'Gulabjamun','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (44,'Halva','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (45,'Idli','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (46,'Indian-mix','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (47,'Indianomelette','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (48,'Jalebi','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (49,'Jhalmuri','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (50,'Kachori','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (51,'Kalathappam','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (52,'Katiroll','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (53,'Kebab','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (54,'Kesari','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (55,'Khakhra','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (56,'Khaman','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (57,'Khandvi','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (58,'Kinnathappam','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (59,'Kosambari','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (60,'Laddoo','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (61,'Lukhmi','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (62,'Maddurvada','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (63,'MakkaPoha','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (64,'Malapua','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (65,'Mangalorebajji','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (66,'Masalapuri','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (67,'MirchiBajji','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (68,'Modak','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (69,'Momo','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (70,'Murukku','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (71,'Mysorepak','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (72,'MisalPav','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (73,'Namakpara','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (74,'Namkeen','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (75,'Neyyappam','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (76,'Pakora','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (77,'Pakwan','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (78,'Palappam','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (79,'Paneertikka','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (80,'Panipuri','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (81,'PapadamorPapad','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (82,'Paprichaat','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (83,'Paratha','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (84,'Parotta','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (85,'PavBhaji','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (86,'Piyaju','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (87,'Pohe','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (88,'Ponganalu','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (89,'Poornalu','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (90,'Pootharekulu','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (91,'Potatochips','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (92,'Puffedrice','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (93,'Puffs','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (94,'Punugulu','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (95,'PuranPoli','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (96,'Puri','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (97,'Puribhaji','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (98,'Ravaladdu','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (99,'Rosomelette','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (100,'Sabudanapapad','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (101,'Sabudanakhichri','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (102,'Sabudanavada','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (103,'Sakinalu','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (104,'Samosa','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (105,'Sandige','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (106,'Sandwich','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (107,'SarvaPindi','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (108,'Sevmamra','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (109,'Shankarpali','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (110,'Shrikhand','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (111,'Tele-bhaja','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (112,'ThaliPeeth','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (113,'Upma','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (114,'Vadapav','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (115,'Vadai','indian',f,f,t,'snacks','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (116,'Machher Jhol','east indian',f,t,f,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (117,'Pork jarpaa jurpie','east indian',f,t,f,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (118,'Chak-Hao Kheer','east indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (119,'Galho','east indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (120,'Achari baingan','east indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (121,'Aloo gobi','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (122,'Aloo tikki','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (123,'Aloo tuk','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (124,'Aloo matar','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (125,'Aloo kulcha','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (126,'Aloo methi','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (127,'Aloo shimla mirch','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (128,'Amriti with rabdi','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (129,'Talit Macchi','north indian',f,t,f,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (130,'Baati','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (131,'Bhatura','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (132,'Bhindi masala','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (133,'Butter chicken','north indian',f,t,f,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (134,'Chaat','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (135,'Chana masala','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (136,'Chapati','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (137,'Chicken razala','north indian',f,t,f,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (138,'Chicken Tikka','north indian',f,t,f,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (139,'Chicken Tikka masala','north indian',f,t,f,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (140,'Chole bhature','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (141,'Daal baati churma','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (142,'Daal puri','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (143,'Dal makhani (kali dal)','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (144,'Dal fara','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (145,'Dal','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (146,'Dal fry with tadka','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (147,'Dum aloo','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (148,'Poha','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (149,'Fara','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (150,'phirni','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (151,'Aloo Phalliyaan','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (152,'Gajar Pak[2]','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (153,'Gajar matar aloo','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (154,'Gobhi matar','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (155,'Imarti','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (156,'Hari mutter ka nimona (green peas daal)','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (157,'Jalebi','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (158,'Jaleba','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (159,'Kachori','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (160,'Kadai paneer','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (161,'Kadhi pakoda','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (162,'Karela bharta','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (163,'Katha meetha petha / kaddu halwa','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (164,'Kheer','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (165,'Khichdi','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (166,'Kadhi and Khichdi','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (167,'Kofta','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (168,'Kulfi falooda','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (169,'Laapsi','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (170,'Lauki ke kofte','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (171,'Lauki ki bhaaji','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (172,'Litti chokha','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (173,'Makhaan ka kheer','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (174,'Makki ki roti, sarson ka saag','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (175,'Mathura ke pede','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (176,'Methi saag, chaulai saag','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (177,'Millet Lapsi','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (178,'Missi roti','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (179,'Mixed vegetable','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (180,'Moong dal ki Lapsi','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (181,'Murgh musallam','north indian',f,t,f,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (182,'Mushroom do pyaza (Kanda Khumb)','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (183,'Mushroom matar (Matar Khumb)','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (184,'Naan','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (185,'Navrattan korma','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (186,'Pakhala','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (187,'Palak paneer','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (188,'Paneer butter masala','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (189,'Paneer tikka masala','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (190,'Pani puri','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (191,'Panjeeri','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (192,'Papad','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (193,'Paratha','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (194,'Pattor','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (195,'Pinni','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (196,'Rajma chaval','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (197,'Rajma','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (198,'Ramatori bhaaji','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (199,'Lobiya','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (200,'Samosa','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (201,'Samose','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (202,'Sattu ki roti','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (203,'Rajwadi Chhena/Paneer[4]','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (204,'Shahi tukra','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (205,'Singhada Lapsi','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (206,'Sooji halwa (Suji Lapsi)','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (207,'Sweet pethas / kesar petha / pista petha','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (208,'Vegetable jalfrezi','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (209,'Tandoori Chicken','north indian',f,t,f,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (210,'Tamatar Chaat','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (211,'Tandoori Fish Tikka','north indian',f,t,f,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (212,'ananas menaskai','north indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (213,'Attu','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (214,'Aval kesari','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (215,'Avial','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (216,'Baida roti','south indian',f,t,f,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (217,'Halwa','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (218,'Bhajji','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (219,'Biryani','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (220,'Bisi bele bath (Karnataka)','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (221,'Bonda','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (222,'Chettinadu Chicken','south indian',f,t,f,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (223,'Chicken 65','south indian',f,t,f,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (224,'Currivepillai sadam (Tamil Nadu)','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (225,'Dibba rotti','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (226,'Dosa','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (227,'Double ka meetha','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (228,'Ennai kathirikkai','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (229,'Goli bajje','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (230,'Hyderabadi biryani','south indian',f,t,f,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (231,'Idiyappam','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (232,'Idli','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (233,'Indian omelette','south indian',f,t,f,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (234,'Kaara kozhambu (Tamil Nadu)','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (235,'Kanji','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (236,'Keerai koottu (Tamil Nadu)','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (237,'Keerai masiyal','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (238,'Keerai poriyal','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (239,'Keerai sadam (Tamil Nadu)','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (240,'Kerala Beef Fry','south indian',f,t,f,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (241,'Kodubale','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (242,'kolhapuri akkha masoor Dal','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (243,'Koottu','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (244,'Kori rotti','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (245,'Kos kootu','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (246,'Koshambri','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (247,'Kothamali sadam','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (248,'Kuzhakkattai','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (249,'Kuzhambu','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (250,'Masala Dosa','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (251,'Nandu omelette','south indian',f,t,f,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (252,'Obbattu (holige, bobbattu, pooran-poli)','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (253,'Olan (dish)','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (254,'Pachadi','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (255,'Paniyaram, Paddu, Gunthapangnalu','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (256,'Papadum','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (257,'Paravannam','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (258,'Parotta','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (259,'Paruppu sadam','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (260,'Payasam','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (261,'Pesarattu','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (262,'Pongal','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (263,'Poriyal','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (264,'Puli sadam, Puliogre, Puliohara','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (265,'Puttu','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (266,'Ragi mudhe, Kali','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (267,'Rasam','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (268,'Sajjige','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (269,'Sakkara pongal','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (270,'Sambar','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (271,'Sandige (Karnataka),Vattral','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (272,'Sevai','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (273,'Sponge dosa','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (274,'Thattai','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (275,'Thayir sadam, mosaranna, perugannam','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (276,'Theeyal','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (277,'Thengai sadam','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (278,'Uttapam Tamil Nadu','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (279,'Vada','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (280,'Varuval','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (281,'Wheat upma, Uppittu','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (282,'Yelumicham sadam, chitranna','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (283,'Amti','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (284,'Bajri no rotlo','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (285,'Batata Saung','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (286,'Barfi','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (287,'Basundi','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (288,'Bhakri','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (289,'Bombil fry','gujrati',f,t,f,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (290,'Chevdo','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (291,'Cholafali','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (292,'Chorafali','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (293,'Daal Dhokli','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (294,'Dabeli','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (295,'Dahi vada','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (296,'Dalithoy','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (297,'Dhokla','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (299,'Dudhi no halwo','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (300,'dudhi muthiya','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (301,'Dum aaloo','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (302,'Gajar halwo','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (303,'Gatta curry','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (304,'Ghari (sweet from Surat)','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (305,'Ghooghra','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (306,'Gud papdi (Gol papdi)','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (307,'Gulab jamun','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (308,'Halvasan','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (309,'Handwo (steamed dish)','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (310,'Gur','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (311,'Jeera Aloo','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (312,'Juvar no rotlo','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (313,'Kansar','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (314,'Karanji','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (315,'Keri no ras','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (316,'Khakhra','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (317,'Khandvi','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (318,'Kombdi vade','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (319,'Kopra paak','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (320,'Koshimbir','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (321,'Kolim / Jawla','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (322,'Laddu','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (323,'Locha','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (324,'Malpua','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (325,'Methi na Gota','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (326,'Modak','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (327,'Mohanthal','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (328,'Chakri (chakali)','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (329,'Muthiya','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (330,'Naralachi vadi / Khobryachi vadi / Coconut vadi','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (331,'Oondees','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (332,'Panipuri','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (333,'Patra','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (334,'Pav Bhaji','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (335,'Penda','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (336,'Pooran-poli','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (337,'Poori','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (338,'Puri Bhaji','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (339,'Rasya muthia','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (340,'Sabudana Khichadi','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (341,'Saath','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (342,'Sev khamani','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (343,'Sev tameta','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (344,'Shakarpara','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (345,'Namakpara','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (346,'Shankarpali','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (347,'Shiro','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (348,'Shrikhand','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (349,'Sohan papdi','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (350,'Soonvali','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (351,'Sukhdi','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (352,'Surnoli','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (353,'Sutarfeni','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (354,'Thalipeeth','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (355,'Thepla','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (356,'Undhiyu','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (357,'Upmaa','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (358,'Vada pav','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (359,'Veg Kolhapuri','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (360,'Vindaloo','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (361,'Ghebar or Ghevar','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (362,'Lilva Kachori','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (363,'Maghaz','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (364,'Mag Dhokli','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (365,'Khichu','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (366,'Farsi Puri','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (367,'Khaman','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (368,'Turiya Patra Vatana sabji','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (369,'Mohan thaal','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (370,'Churma Ladoo','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (371,'Zunka or Pitla','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (372,'Cheera Doi','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (373,'Daab chingri','gujrati',f,t,f,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (374,'Dhup Pitha','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (375,'Gheela Pitha','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (376,'Hurum','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (377,'Khar','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (378,'Kumol Sawul','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (379,'Loskora (Coconut Laddu)','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (380,'Luchi (food)|Luchi','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (381,'Malpua/Malpoa','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (382,'Momo','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (383,'Muri Naaru','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (384,'Pani Tenga','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (385,'Sunga Pitha','gujrati',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (386,'Alu Pitika','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (387,'Masor tenga','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (388,'Bengena Pitika','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (389,'Bilahi Maas','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (390,'Black rice','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (391,'Bora Sawul','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (392,'Brown Rice','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (393,'Chhenagaja','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (394,'Chhenapoda','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (395,'Chingri malai curry','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (396,'Goja','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (397,'Hando Guri','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (399,'Horioh Maas','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (400,'Ilish or Chingri Bhape','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (401,'Kabiraji','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (402,'Kharoli','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (403,'Khorisa','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (404,'Koldil Chicken','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (405,'Koldil Duck','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (406,'Konir Dom','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (407,'Lai Haq Maas','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (408,'Litti','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (409,'Maasor Tenga','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (410,'Machher Jhol','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (411,'Masor Koni','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (412,'Masor Petu','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (413,'Mishti Chholar Dal','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (414,'Mishti Doi','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (415,'Ou tenga Maas','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (416,'Bhaji','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (417,'Pani Pitha','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (418,'Pantua','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (419,'Payokh','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (420,'Peda','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (421,'Prawn malai curry','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (422,'Red Rice','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (423,'Rice','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (424,'Rasagola/Roshogolla','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (425,'Shondesh','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (426,'Shukto','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (427,'Sunga Pork','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (428,'Tenga Doi','south indian',f,t,t,'maincourse','Indian');",
            "insert into food (id,dish,cuisine,beverage,hot,veg,course,region) values (429,'Til Pitha','south indian',f,t,t,'maincourse','Indian');"
    };
}
